name: SonarCloud
run-name: SonarCloud analysis
on:
  workflow_run:
    workflows: ["Units Tests"]
    types:
      - completed

jobs:
  back-end:
    name: Back-end
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=bobapp_backend

  front-end:
    name: Front-end
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: front
          args: >
            -Dsonar.organization=paulmarniquet
            -Dsonar.projectKey=bobapp_frontend
            -Dsonar.sources=src/
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
