name: Units Tests
run-name: Unit tests

on:
  push:
    branches: [ main ]
    
jobs:
#  backend-unit-tests:
#    name: Back-end
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./back
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '11'
#
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml
#
#      - name: Units tests
#        run: mvn -B test --file pom.xml jacoco:report
#
#      - name: Upload JaCoCo coverage report as a workflow artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: jacoco-report
#          path: back/target/site/jacoco/
#
#      - name: Get the Coverage info
#        run: |
#          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
#          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"


  frontend-unit-tests:
    name: Front-end
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v2
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - run: npm ci
      - run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage

      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report
        if: success() || failure()
        with:
          name: Karma Tests
          path: ./coverage/bobapp/*.html
          reporter: jest-junit
