name: Units Tests
run-name: Unit tests

on:
  push:
    branches: [ main ]
    
jobs:
#  backend-unit-tests:
#    name: Back-end
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./back
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '11'
#
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml
#
#      - name: Units tests
#        run: mvn -B test --file pom.xml jacoco:report
#
#      - name: Upload JaCoCo coverage report as a workflow artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: jacoco-report
#          path: back/target/site/jacoco/
#
#      - name: Get the Coverage info
#        run: |
#          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
#          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"


  frontend-unit-tests:
    name: Front-end
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v2

      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci

      - name: Launch Karma tests
        run: npm run test:prod

      - uses: actions/upload-artifact@v3
        with:
          name: Karma Tests Reports
          path: front/coverage
