name: Mon workflow principal

on:
  push:
    branches:
      - main

jobs:
  mon_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests unitaires
        uses: ./tests.yaml
      - name: SonarCloud
        uses: ./sonar.yaml
      - name: Dockerize
        uses: ./dockerize.yaml
